### PR TITLE
symfony_route_translate

### PR DESCRIPTION
**Pull request by Suvres**
new PR to [issue13](https://github.com/migrify/migrify/issues/13)

### CODE REVIEW

**Comment by Suvres** [comment]
Hey,
@TomasVotruba can you, look on this PR. I make it for  [issue13](https://github.com/migrify/migrify/issues/13)

**Comment by Suvres** [comment]
@TomasVotruba @ThomasLandauer

**Comment by TomasVotruba** [comment]
Hi, I didn't get to this PR as CI is failing.
We need it green before review

**Comment by TomasVotruba** [comment]
The @migrify packages are moving to @symplify, to improve support and give more focus on development.

So is the routing package. If you wan't to contribute, please re-submit the PR there. Thank you

**Pull request closed without merging**
