### PR TITLE
[VendorPatches] Refactor to Composer plugin

### PR DESCRIPTION
**Pull request by kasperg**
This is an initial stab at #31.

A couple of notes:

- I tried to follow the standards and practices of the package as best as I could
- I tore out the dependency injection setup because I could not determine how it could fit into the Composer plugin. This is not really intentional and I would like to examine how I can put it back.

The current version of this package is a standalone Symfony Console
application which only works with packages installed in the vendor
directory. This is unfortunate because it prevents usage for packages
installed elsewhere typically managed by the composer/installers
project.

To be able to determine where a packages is installed vendor-patches
needs to retrieve this information from Composer. One way to achieve
this is to implement vendor-patches as a Composer plugin.

This provides access to the installation manager which can provide
the installation directory for a package. This way a lot of the
current logic for determining package directories becomes obsolete.

Also Composer plugins can provide commands and thus vendor-patches no
longer need to work as a standalone Symfony Console application.

Here we update the definition of the package and the central
Generate Command to work as a Composer plugin. Patch detection is now
executed on a per directory level with Composer providing more
detailed package information and more detailed patch information
being returned as well through new value objects.

All obsolete classes and tests are removed and documentation is
updated accordingly.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This kinda removes the whole tool, not a way to go :thinking:  

Please keep the original code and make the plugin as standalone subpackage, e.g. in

```bash
/packages/vendor-patches
/packages/vendor-patches-composer-plugin
```

**Comment by kasperg** [comment]
The parts that should be removed are `PackageNameResolver`, `PathResolver`, `VendorPatchesApplication` and the `vendor-patches` bin. I think all are made obsolete by data and infrastructure provided by Composer itself.

`PackageNameResolver` and `PathResolver` work to determine information about packages that can be reliably retrieved from the Composer `InstallationManager`. This approach is also used by [`cweagons/composer-patches`](https://github.com/cweagans/composer-patches/blob/master/src/Plugin/Patches.php#L306). If you put side the `composer/installers` compatibility argument the current approach will not work if you use Composers [`vendor_dir` configuration option](https://getcomposer.org/doc/06-config.md#vendor-dir).

Personally I do not see the value of the standalone application. Composer provides the foundation for the package to be executed so we can write and maintain less code and remove a dependency.

For a tool that works so closely with Composer, I think this is the right direction to go. I cannot see how implementing it as a subpackage would work without a major refactoring of the existing codebase anyway. If you can provide some more direction I would be happy to look again.

All that being said: Your work, your decision 😃 .

**Comment by TomasVotruba** [comment]
Nothing needs to be removed, we can have one code code and profiled implementation. As doctrine + doctrine bundle.

**Comment by kasperg** [comment]
Sorry. I cannot see how that would work and and I do not really see the value in it either. I'll close this for now.

I will probably keep the change around in the current state in some form as someone might find it useful.

**Comment by TomasVotruba** [comment]
Same way doctrine/doctrine-bundle uses doctrine/orm without touching it

**Comment by kasperg** [comment]
For subpackaging to work there would either have to be changes to other parts of the project like `Differ` and `OldToNewFilesFinder` to accommodate this. That goes against the principle of not touching the package. Otherwise the shared codebase would be extremely limited. That limits the usefulness of using subpackages.

I see your reference to Doctrine but I cannot see the value of applying this to the current situation. `doctrine/orm` is intentionally framework agnostic. `doctrine/doctrine-bundle` integrates Doctrine with Symfony. `vendor-patches` is already integrated with Composer. I do not know what other context you would want to use the package.

**Comment by TomasVotruba** [comment]
I never wrote composer plugin, so my knowledge is limited. I just use common sense of integrating packages together. When I need plugin, I wrap around existing package.

If that's not possible for composer for some unknown reason, then I recommend making own package where you can re-use code of migrify package and complete rewrite to your needs :+1:

**Pull request closed without merging**
